In [1]:
import pandas as pd
import numpy as np

# 1.检查索引

In [2]:
#读取college数据集，提取所有的列
college = pd.read_csv('data/college.csv')
columns = college.columns
columns

Index(['INSTNM', 'CITY', 'STABBR', 'HBCU', 'MENONLY', 'WOMENONLY', 'RELAFFIL',
       'SATVRMID', 'SATMTMID', 'DISTANCEONLY', 'UGDS', 'UGDS_WHITE',
       'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI',
       'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN', 'PPTUG_EF', 'CURROPER', 'PCTPELL',
       'PCTFLOAN', 'UG25ABV', 'MD_EARN_WNE_P10', 'GRAD_DEBT_MDN_SUPP'],
      dtype='object')

In [3]:
#用values属性，访问底层的numpy数组
columns.values

array(['INSTNM', 'CITY', 'STABBR', 'HBCU', 'MENONLY', 'WOMENONLY',
       'RELAFFIL', 'SATVRMID', 'SATMTMID', 'DISTANCEONLY', 'UGDS',
       'UGDS_WHITE', 'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN',
       'UGDS_NHPI', 'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN', 'PPTUG_EF',
       'CURROPER', 'PCTPELL', 'PCTFLOAN', 'UG25ABV', 'MD_EARN_WNE_P10',
       'GRAD_DEBT_MDN_SUPP'], dtype=object)

In [4]:
#取出该数组的第6个值
columns[5]

'WOMENONLY'

In [5]:
#取出该数组的第2,9,11
columns[[1,8,10]]

Index(['CITY', 'SATMTMID', 'UGDS'], dtype='object')

In [6]:
#逆序切片选取
columns[-7:-4]

Index(['PPTUG_EF', 'CURROPER', 'PCTPELL'], dtype='object')

In [7]:
#索引有许多和Series和DataFrame相同的方法
columns.min(),columns.max(),columns.isnull().sum()

('CITY', 'WOMENONLY', 0)

In [8]:
#索引对象可以直接通过字符串方法修改
columns + '_A'

Index(['INSTNM_A', 'CITY_A', 'STABBR_A', 'HBCU_A', 'MENONLY_A', 'WOMENONLY_A',
       'RELAFFIL_A', 'SATVRMID_A', 'SATMTMID_A', 'DISTANCEONLY_A', 'UGDS_A',
       'UGDS_WHITE_A', 'UGDS_BLACK_A', 'UGDS_HISP_A', 'UGDS_ASIAN_A',
       'UGDS_AIAN_A', 'UGDS_NHPI_A', 'UGDS_2MOR_A', 'UGDS_NRA_A',
       'UGDS_UNKN_A', 'PPTUG_EF_A', 'CURROPER_A', 'PCTPELL_A', 'PCTFLOAN_A',
       'UG25ABV_A', 'MD_EARN_WNE_P10_A', 'GRAD_DEBT_MDN_SUPP_A'],
      dtype='object')

In [10]:
#索引对象也可以通过比较运算符，得到BOOL索引
columns > 'G'

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True])

In [12]:
#尝试用赋值的方法，修改索引对象的一个值，会导致类型错误，因为索引对象是不可变类型
columns[1] = 'city'

TypeError: Index does not support mutable operations

In [13]:
#索引对象支持集合运算：联合、交叉、求差、对称差
#切片
c1 = columns[:4]
c1

Index(['INSTNM', 'CITY', 'STABBR', 'HBCU'], dtype='object')

In [14]:
c2 = columns[2:5]
c2

Index(['STABBR', 'HBCU', 'MENONLY'], dtype='object')

In [15]:
#联合
c1.union(c2)

Index(['CITY', 'HBCU', 'INSTNM', 'MENONLY', 'STABBR'], dtype='object')

In [16]:
c1 | c2

Index(['CITY', 'HBCU', 'INSTNM', 'MENONLY', 'STABBR'], dtype='object')

In [17]:
#对称差
c1.symmetric_difference(c2)

Index(['CITY', 'INSTNM', 'MENONLY'], dtype='object')

In [18]:
c1 ^ c2

Index(['CITY', 'INSTNM', 'MENONLY'], dtype='object')

# 2.求笛卡尔积

In [19]:
#创建两个有不同索引、但包含一些相同值得Series
s1 = pd.Series(index=list('aaab'),data=np.arange(4))
s1

a    0
a    1
a    2
b    3
dtype: int32

In [20]:
s2 = pd.Series(index=list('cababb'),data=np.arange(6))
s2

c    0
a    1
b    2
a    3
b    4
b    5
dtype: int32

In [21]:
#二者相加，以产生一个笛卡尔积
s1 + s2

a    1.0
a    3.0
a    2.0
a    4.0
a    3.0
a    5.0
b    5.0
b    7.0
b    8.0
c    NaN
dtype: float64

In [22]:
#当两组索引元素完全相同、顺序也相同时，不会生成笛卡尔积；
#索引会按照它们的位置对齐。
#下面两个Series完全相同，结果也是整数
s1 = pd.Series(index=list('aaabb'),data=np.arange(5))
s2 = pd.Series(index=list('aaabb'),data=np.arange(5))
s1 + s2

a    0
a    2
a    4
b    6
b    8
dtype: int32

In [23]:
#如果索引元素相同，但顺序不同，是能产生笛卡尔积的
s1 = pd.Series(index=list('aaabb'),data=np.arange(5))
s2 = pd.Series(index=list('bbaaa'),data=np.arange(5))
s1 + s2

a    2
a    3
a    4
a    3
a    4
a    5
a    4
a    5
a    6
b    3
b    4
b    4
b    5
dtype: int32

# 3.索引爆炸

In [24]:
#读取employee数据集，设定行索引是RACE
employee = pd.read_csv('data/employee.csv',index_col='RACE')
employee.head()

,UNIQUE_ID,POSITION_TITLE,DEPARTMENT,BASE_SALARY,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE
RACE,,,,,,,,,
Hispanic/Latino,0,ASSISTANT DIRECTOR (EX LVL),Municipal Courts Department,121862.0,Full Time,Female,Active,2006-06-12,2012-10-13
Hispanic/Latino,1,LIBRARY ASSISTANT,Library,26125.0,Full Time,Female,Active,2000-07-19,2010-09-18
White,2,POLICE OFFICER,Houston Police Department-HPD,45279.0,Full Time,Male,Active,2015-02-03,2015-02-03
White,3,ENGINEER/OPERATOR,Houston Fire Department (HFD),63166.0,Full Time,Male,Active,1982-02-08,1991-05-25
White,4,ELECTRICIAN,General Services Department,56347.0,Full Time,Male,Active,1989-06-19,1994-10-22

In [25]:
#选取BASE_SALARY做成两个Series，判断二者是否相同
salary1 = employee['BASE_SALARY']
salary2 = employee['BASE_SALARY']
salary1 is salary2

True

In [26]:
#结果是True，表明二者指向的同一个对象；
#意味着，如果修改一个，另一个也会改变；
#所以复制数据，使用copy()最好。
salary1 = employee['BASE_SALARY'].copy()
salary2 = employee['BASE_SALARY'].copy()
salary1 is salary2

False

In [27]:
#对其中一个做索引排序，比较二者是否不同
salary1 = salary1.sort_index()
salary1.head()

RACE
American Indian or Alaskan Native    78355.0
American Indian or Alaskan Native    26125.0
American Indian or Alaskan Native    98536.0
American Indian or Alaskan Native        NaN
American Indian or Alaskan Native    55461.0
Name: BASE_SALARY, dtype: float64

In [28]:
salary2.head()

RACE
Hispanic/Latino    121862.0
Hispanic/Latino     26125.0
White               45279.0
White               63166.0
White               56347.0
Name: BASE_SALARY, dtype: float64

In [29]:
#将两个Series相加
salary_add = salary1 + salary2
salary_add.head()

RACE
American Indian or Alaskan Native    138702.0
American Indian or Alaskan Native    156710.0
American Indian or Alaskan Native    176891.0
American Indian or Alaskan Native    159594.0
American Indian or Alaskan Native    127734.0
Name: BASE_SALARY, dtype: float64

In [30]:
#再将salary1与其自身相加；
#查看几个所得结果的长度，可以看到长度从2000到达117万了
salary_add1 = salary1 + salary1
len(salary1),len(salary2),len(salary_add),len(salary_add1)

(2000, 2000, 1175424, 2000)

In [31]:
#验证salary_add值的个数。因为笛卡尔积是作用在相同索引元素上的，可以对其平方值求和
index_vc = salary1.index.value_counts(dropna=False)
index_vc

Black or African American            700
White                                665
Hispanic/Latino                      480
Asian/Pacific Islander               107
NaN                                   35
American Indian or Alaskan Native     11
Others                                 2
Name: RACE, dtype: int64

In [32]:
index_vc.pow(2).sum()

1175424

# 4.用不等索引填充数值

In [33]:
#读取三个baseball数据集，行索引设为playerID
baseball_14 = pd.read_csv('data/baseball14.csv',index_col='playerID')
baseball_15 = pd.read_csv('data/baseball15.csv',index_col='playerID')
baseball_16 = pd.read_csv('data/baseball16.csv',index_col='playerID')
baseball_14.head()

,yearID,stint,teamID,lgID,G,AB,R,H,2B,3B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
playerID,,,,,,,,,,,,,,,,,,,,,
altuvjo01,2014,1,HOU,AL,158,660,85,225,47,3,...,59.0,56.0,9.0,36,53.0,7.0,5.0,1.0,5.0,20.0
cartech02,2014,1,HOU,AL,145,507,68,115,21,1,...,88.0,5.0,2.0,56,182.0,6.0,5.0,0.0,4.0,12.0
castrja01,2014,1,HOU,AL,126,465,43,103,21,2,...,56.0,1.0,0.0,34,151.0,1.0,9.0,1.0,3.0,11.0
corpoca01,2014,1,HOU,AL,55,170,22,40,6,0,...,19.0,0.0,0.0,14,37.0,0.0,3.0,1.0,2.0,3.0
dominma01,2014,1,HOU,AL,157,564,51,121,17,0,...,57.0,0.0,1.0,29,125.0,2.0,5.0,2.0,7.0,23.0

In [34]:
#用索引方法difference，找到哪些索引标签在baseball_14中，
#却不在baseball_15、baseball_16中
baseball_14.index.difference(baseball_15.index)

Index(['corpoca01', 'dominma01', 'fowlede01', 'grossro01', 'guzmaje01',
       'hoeslj01', 'krausma01', 'preslal01', 'singljo02'],
      dtype='object', name='playerID')

In [35]:
baseball_14.index.difference(baseball_16.index)

Index(['cartech02', 'corpoca01', 'dominma01', 'fowlede01', 'grossro01',
       'guzmaje01', 'hoeslj01', 'krausma01', 'preslal01', 'singljo02',
       'villajo01'],
      dtype='object', name='playerID')

In [38]:
#找到每名球员在过去三个赛季的击球数，H列包含了这个数据
hits_14 = baseball_14['H']
hits_15 = baseball_15['H']
hits_16 = baseball_16['H']
hits_14.head()

playerID
altuvjo01    225
cartech02    115
castrja01    103
corpoca01     40
dominma01    121
Name: H, dtype: int64

In [39]:
#将hits_14和hits_15两列相加
(hits_14 + hits_15).head()

playerID
altuvjo01    425.0
cartech02    193.0
castrja01    174.0
congeha01      NaN
corpoca01      NaN
Name: H, dtype: float64

In [40]:
#congeha01和corpoca01在2015年是有记录的，但是结果缺失了。
#使用add方法和参数fill_value，避免产生缺失值
hits_14.add(hits_15,fill_value=0).head()

playerID
altuvjo01    425.0
cartech02    193.0
castrja01    174.0
congeha01     46.0
corpoca01     40.0
Name: H, dtype: float64

In [41]:
#再将2016的数据也加上
hits_total = hits_14.add(hits_15,fill_value=0).add(hits_16,fill_value=0)
hits_total.head()

playerID
altuvjo01    641.0
bregmal01     53.0
cartech02    193.0
castrja01    243.0
congeha01     46.0
Name: H, dtype: float64

In [42]:
#检查结果中是否有缺失值
hits_total.hasnans

False

In [43]:
#如果一个元素在两个Series都是缺失值，即便使用了fill_value，相加的结果仍是缺失值
s = pd.Series(index=['a','b','c','d'],data=[np.nan,3,np.nan,1])
s

a    NaN
b    3.0
c    NaN
d    1.0
dtype: float64

In [44]:
s1 = pd.Series(index=['a','b','c'],data=[np.nan,6,10])
s1

a     NaN
b     6.0
c    10.0
dtype: float64

In [45]:
s.add(s1,fill_value=5)

a     NaN
b     9.0
c    15.0
d     6.0
dtype: float64

In [46]:
s1.add(s,fill_value=5)

a     NaN
b     9.0
c    15.0
d     6.0
dtype: float64

In [49]:
#从baseball_14中选取一些列
df_14 = baseball_14[['G','AB','R','H']]
df_14.head()

             G   AB   R    H
playerID
altuvjo01  158  660  85  225
cartech02  145  507  68  115
castrja01  126  465  43  103
corpoca01   55  170  22   40
dominma01  157  564  51  121

In [50]:
#再从baseball_15中选取一些列，有相同的、也有不同的
df_15 = baseball_15[['AB','R','H','HR']]
df_15.head()

            AB   R    H  HR
playerID
altuvjo01  638  86  200  15
cartech02  391  50   78  24
castrja01  337  38   71  11
congeha01  201  25   46  11
correca01  387  52  108  22

In [51]:
#将二者相加的话，只要行或列不能对齐，就会产生缺失值。
#style属性的highlight_null方法可以高亮缺失值
(df_14 + df_15).head(10).style.highlight_null('yellow')

In [53]:
#即便使用了fill_value=0,有些值也会是缺失值，
#这是因为一些行和列的组合根本不存在输入的数据中
df_14.add(df_15,fill_value=0).head(10).style.highlight_null('yellow')

# 5.从不同的DataFrame追加列

In [57]:
#读取employee数据，选取‘DEPARTMENT’,'BASE_SALARY'这两列
employee = pd.read_csv('data/employee.csv')
dept_sal = employee[['DEPARTMENT','BASE_SALARY']]
#在每个部门内，对BASE_SALARY进行排序
dept_sal = dept_sal.sort_values(['DEPARTMENT','BASE_SALARY'],ascending=[True,False])
#用drop_duplicates方法保留每个部门的第一行
max_dept_sal = dept_sal.drop_duplicates(subset='DEPARTMENT')
max_dept_sal.head()

                        DEPARTMENT  BASE_SALARY
1494    Admn. & Regulatory Affairs     140416.0
149       City Controller's Office      64251.0
236                   City Council     100000.0
647   Convention and Entertainment      38397.0
1500   Dept of Neighborhoods (DON)      89221.0

In [58]:
#使用DEPARTMENT作为行索引
max_dept_sal = max_dept_sal.set_index('DEPARTMENT')
employee = employee.set_index('DEPARTMENT')
#现在行索引包含匹配值了，可以向employee的DataFrame新增一列
employee['MAX_DEPT_SALARY'] = max_dept_sal['BASE_SALARY']
pd.options.display.max_columns = 6
employee

,UNIQUE_ID,POSITION_TITLE,BASE_SALARY,...,HIRE_DATE,JOB_DATE,MAX_DEPT_SALARY
DEPARTMENT,,,,,,,
Municipal Courts Department,0,ASSISTANT DIRECTOR (EX LVL),121862.0,...,2006-06-12,2012-10-13,121862.0
Library,1,LIBRARY ASSISTANT,26125.0,...,2000-07-19,2010-09-18,107763.0
Houston Police Department-HPD,2,POLICE OFFICER,45279.0,...,2015-02-03,2015-02-03,199596.0
Houston Fire Department (HFD),3,ENGINEER/OPERATOR,63166.0,...,1982-02-08,1991-05-25,210588.0
General Services Department,4,ELECTRICIAN,56347.0,...,1989-06-19,1994-10-22,89194.0
Houston Police Department-HPD,5,SENIOR POLICE OFFICER,66614.0,...,1984-11-26,2005-03-26,199596.0
Public Works & Engineering-PWE,6,ENGINEER,71680.0,...,2012-03-26,2012-03-26,178331.0
Houston Airport System (HAS),7,CARPENTER,42390.0,...,2013-11-04,2013-11-04,186192.0
Public Works & Engineering-PWE,8,DEPUTY ASSISTANT DIRECTOR (EXECUTIVE LEV,107962.0,...,1993-11-15,2013-01-05,178331.0
Houston Airport System (HAS),9,AIRPORT OPERATIONS COORDINATOR,44616.0,...,2016-03-14,2016-03-14,186192.0
Houston Fire Department (HFD),10,FIRE FIGHTER,52644.0,...,2007-05-21,2008-11-15,210588.0
Health & Human Services,11,"CHIEF PHYSICIAN,MD",180416.0,...,1987-05-22,1999-08-28,180416.0
Public Works & Engineering-PWE,12,CUSTOMER SERVICE REPRESENTATIVE I,30347.0,...,2015-11-16,2015-11-16,178331.0
Health & Human Services,13,PUBLIC HEALTH INVESTIGATOR SUPERVISOR,55269.0,...,1999-10-20,2001-05-19,180416.0
Houston Police Department-HPD,14,POLICE SERGEANT,77076.0,...,2001-06-04,2015-05-25,199596.0
Houston Police Department-HPD,15,SENIOR POLICE OFFICER,NaN,...,1995-01-30,2015-02-14,199596.0
Houston Police Department-HPD,16,SENIOR POLICE OFFICER,NaN,...,1981-02-23,2002-01-05,199596.0
Houston Police Department-HPD,17,POLICE SERGEANT,81239.0,...,1995-06-19,2007-03-03,199596.0
General Services Department,18,MAINTENANCE MECHANIC III,40581.0,...,2008-12-29,2008-12-29,89194.0
Houston Police Department-HPD,19,SENIOR POLICE OFFICER,66614.0,...,1992-02-17,2007-07-28,199596.0
Public Works & Engineering-PWE,20,SENIOR INSPECTOR,61506.0,...,2009-04-06,2015-04-11,178331.0
Houston Fire Department (HFD),21,FIRE FIGHTER,57815.0,...,2001-03-20,2003-01-04,210588.0
Public Works & Engineering-PWE,22,INSPECTOR,43264.0,...,2015-01-05,2015-01-05,178331.0
Houston Fire Department (HFD),23,FIRE FIGHTER,55437.0,...,2004-03-15,2005-03-26,210588.0
Houston Police Department-HPD,24,POLICE OFFICER,52514.0,...,2010-03-29,2011-03-29,199596.0
Houston Police Department-HPD,25,SENIOR POLICE OFFICER,61643.0,...,1999-08-23,2012-03-31,199596.0
Houston Police Department-HPD,26,SENIOR POLICE OFFICER,NaN,...,1979-11-19,2015-12-19,199596.0
Houston Police Department-HPD,27,SENIOR POLICE OFFICER,66614.0,...,1990-01-12,2004-07-03,199596.0
Houston Police Department-HPD,28,POLICE SERGEANT,81239.0,...,1978-03-13,1994-09-10,199596.0
Public Works & Engineering-PWE,29,UTILITY WORKER,29557.0,...,2014-01-21,2014-01-21,178331.0
...,...,...,...,...,...,...,...
Houston Police Department-HPD,1970,SENIOR POLICE OFFICER,66614.0,...,1990-06-11,2002-12-07,199596.0
Houston Police Department-HPD,1971,POLICE OFFICER,45279.0,...,2013-10-14,2014-10-14,199596.0
Houston Fire Department (HFD),1972,ENGINEER/OPERATOR,63166.0,...,1990-12-10,2001-04-28,210588.0
Public Works & Engineering-PWE,1973,SENIOR PROJECT MANAGER,77325.0,...,2008-08-04,2012-07-07,178331.0
Houston Police Department-HPD,1974,SENIOR POLICE OFFICER,66614.0,...,1993-04-12,2013-10-12,199596.0
Houston Airport System (HAS),1975,GROUND TRANSPORTATION REPRESENTATIVE,32157.0,...,1993-05-13,2000-07-15,186192.0
Solid Waste Management,1976,SENIOR SIDELOADER OPERATOR,34466.0,...,2015-07-20,2016-01-30,110005.0
Houston Police Department-HPD,1977,POLICE OFFICER,45279.0,...,2013-06-10,2014-06-10,199596.0
Houston Police Department-HPD,1978,POLICE SERVICE OFFICER,27914.0,...,2011-10-14,2014-03-01,199596.0
Houston Police Department-HPD,1979,SENIOR POLICE OFFICER,66614.0,...,1993-11-08,2006-06-03,199596.0
Houston Police Department-HPD,1980,SENIOR POLICE OFFICER,NaN,...,1983-10-03,2006-05-06,199596.0
Houston Fire Department (HFD),1981,CAPTAIN,70181.0,...,1994-08-29,2013-09-04,210588.0
Houston Fire Department (HFD),1982,FIRE FIGHTER,55437.0,...,2004-01-05,2005-01-14,210588.0
Admn. & Regulatory Affairs,1983,ADMINISTRATIVE SPECIALIST,55172.0,...,2006-10-16,2006-10-16,140416.0
Houston Fire Department (HFD),1984,ENGINEER/OPERATOR,61921.0,...,2006-09-11,2014-06-11,210588.0
Fleet Management Department,1985,TRUCK DRIVER,30222.0,...,2013-06-10,2015-08-01,125884.0
Houston Police Department-HPD,1986,POLICE SERGEANT,77076.0,...,2001-12-03,2010-12-10,199596.0
Houston Police Department-HPD,1987,SENIOR POLICE OFFICER,NaN,...,1977-05-23,2002-01-05,199596.0
Legal Department,1988,SENIOR ASSISTANT CITY ATTORNEY II,124115.0,...,2013-01-23,2013-03-02,275000.0
Public Works & Engineering-PWE,1989,EQUIPMENT WORKER,37211.0,...,1984-12-11,2004-09-18,178331.0
Parks & Recreation,1990,BUILDING MAINTENANCE SUPERVISOR,30347.0,...,1995-10-14,2010-03-20,85055.0
Houston Police Department-HPD,1991,MOBILITY SERVICE OFFICER,44429.0,...,2005-09-12,2007-06-02,199596.0
Houston Airport System (HAS),1992,SECURITY OFFICER,29286.0,...,2011-12-12,2011-12-12,186192.0
Houston Police Department-HPD,1993,POLICE SERGEANT,81239.0,...,1982-05-03,2011-09-03,199596.0
Houston Police Department-HPD,1994,POLICE CAPTAIN,104455.0,...,1983-02-07,2004-07-08,199596.0
Houston Police Department-HPD,1995,POLICE OFFICER,43443.0,...,2014-06-09,2015-06-09,199596.0
Houston Fire Department (HFD),1996,COMMUNICATIONS CAPTAIN,66523.0,...,2003-09-02,2013-10-06,210588.0
Houston Police Department-HPD,1997,POLICE OFFICER,43443.0,...,2014-10-13,2015-10-13,199596.0
Houston Police Department-HPD,1998,POLICE OFFICER,55461.0,...,2009-01-20,2011-07-02,199596.0
Houston Fire Department (HFD),1999,FIRE FIGHTER,51194.0,...,2009-01-12,2010-07-12,210588.0

In [59]:
#现在可以用query查看是否有BASE_SALARY大于MAX_DEPT_SALARY的
employee.query('BASE_SALARY > MAX_DEPT_SALARY')

Empty DataFrame
Columns: [UNIQUE_ID, POSITION_TITLE, BASE_SALARY, RACE, EMPLOYMENT_TYPE, GENDER, EMPLOYMENT_STATUS, HIRE_DATE, JOB_DATE, MAX_DEPT_SALARY]
Index: []

[0 rows x 10 columns]

In [60]:
#用random从dept_sal随机取10行，不做替换
np.random.seed(1234)
random_salary = dept_sal.sample(n=10).set_index('DEPARTMENT')
random_salary

                                BASE_SALARY
DEPARTMENT
Public Works & Engineering-PWE      50586.0
Houston Police Department-HPD       66614.0
Houston Police Department-HPD       66614.0
Housing and Community Devp.         78853.0
Houston Police Department-HPD       66614.0
Parks & Recreation                      NaN
Public Works & Engineering-PWE      37211.0
Public Works & Engineering-PWE      54683.0
Human Resources Dept.               58474.0
Health & Human Services             47050.0

In [61]:
#random_salary中是有重复索引的，employee DataFrame的标签要对应random_salary中的多个标签
employee['RANDOM_DALARY'] = random_salary['BASE_SALARY']

ValueError: cannot reindex from a duplicate axis

In [62]:
#选取max_dept_sal['BASE_SALARY']的前三行，赋值给employee['MAX_SALARY2']
employee['MAX_SALARY2'] = max_dept_sal['BASE_SALARY'].head(3)
#对MAX_SALARY2统计
employee.MAX_SALARY2.value_counts()

140416.0    29
100000.0    11
64251.0      5
Name: MAX_SALARY2, dtype: int64

In [63]:
#因为只填充了三个部门的值，所以其他部门在结果中都是缺失值
employee.MAX_SALARY2.isnull().mean()

0.9775

# 6.高亮每列的最大值

In [64]:
pd.options.display.max_rows = 8
#读取college数据集，INSTNM作为列
college = pd.read_csv('data/college.csv',index_col='INSTNM')
college.dtypes

CITY                   object
STABBR                 object
HBCU                  float64
MENONLY               float64
                       ...
PCTFLOAN              float64
UG25ABV               float64
MD_EARN_WNE_P10        object
GRAD_DEBT_MDN_SUPP     object
Length: 26, dtype: object

In [66]:
#MD_WNE_P10和GRAD_DEBT_MDN_SUPP两列是对象类型，对其进行检查，发现含有字符串
college.MD_EARN_WNE_P10.iloc[0]

'30300'

In [67]:
college.GRAD_DEBT_MDN_SUPP.iloc[0]

'33888'

In [68]:
#降序检查
college.MD_EARN_WNE_P10.sort_values(ascending=False).head()

INSTNM
Sharon Regional Health System School of Nursing    PrivacySuppressed
Northcoast Medical Training Academy                PrivacySuppressed
Success Schools                                    PrivacySuppressed
Louisiana Culinary Institute                       PrivacySuppressed
Bais Medrash Toras Chesed                          PrivacySuppressed
Name: MD_EARN_WNE_P10, dtype: object

In [71]:
#可以用to_numeric，将某列的值做强制转换
cols = ['MD_EARN_WNE_P10','GRAD_DEBT_MDN_SUPP']
for col in cols:
    college[col] = pd.to_numeric(college[col],errors='coerce')
college.dtypes.loc[cols]

MD_EARN_WNE_P10       float64
GRAD_DEBT_MDN_SUPP    float64
dtype: object

In [72]:
#用select_dtypes方法过滤出数值列
college_n = college.select_dtypes(include=[np.number])
college_n.head()

,HBCU,MENONLY,WOMENONLY,...,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,
Alabama A & M University,1.0,0.0,0.0,...,0.1049,30300.0,33888.0
University of Alabama at Birmingham,0.0,0.0,0.0,...,0.2422,39700.0,21941.5
Amridge University,0.0,0.0,0.0,...,0.8540,40100.0,23370.0
University of Alabama in Huntsville,0.0,0.0,0.0,...,0.2640,45500.0,24097.0
Alabama State University,1.0,0.0,0.0,...,0.1270,26600.0,33118.5

In [73]:
#有的列只含有两个值，用nunique()方法挑出这些列
criteria = college_n.nunique() == 2
criteria.head()

HBCU          True
MENONLY       True
WOMENONLY     True
RELAFFIL      True
SATVRMID     False
dtype: bool

In [75]:
#将BOOL Series传给索引运算符，生成二元列的列表
binary_cols = college_n.columns[criteria].tolist()
binary_cols

['HBCU', 'MENONLY', 'WOMENONLY', 'RELAFFIL', 'DISTANCEONLY', 'CURROPER']

In [77]:
#用drop方法删除这些列
college_n2 = college_n.drop(labels=binary_cols,axis='columns')
college_n2.head()

,SATVRMID,SATMTMID,UGDS,...,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,
Alabama A & M University,424.0,420.0,4206.0,...,0.1049,30300.0,33888.0
University of Alabama at Birmingham,570.0,565.0,11383.0,...,0.2422,39700.0,21941.5
Amridge University,NaN,NaN,291.0,...,0.8540,40100.0,23370.0
University of Alabama in Huntsville,595.0,590.0,5451.0,...,0.2640,45500.0,24097.0
Alabama State University,425.0,430.0,4811.0,...,0.1270,26600.0,33118.5

In [78]:
#用idxmax方法选出每列最大值的行索引标签
max_cols = college_n2.idxmax()
max_cols

SATVRMID                      California Institute of Technology
SATMTMID                      California Institute of Technology
UGDS                               University of Phoenix-Arizona
UGDS_WHITE                Mr Leon's School of Hair Design-Moscow
                                         ...
PCTFLOAN                                  ABC Beauty College Inc
UG25ABV                           Dongguk University-Los Angeles
MD_EARN_WNE_P10                     Medical College of Wisconsin
GRAD_DEBT_MDN_SUPP    Southwest University of Visual Arts-Tucson
Length: 18, dtype: object

In [79]:
#用unique()方法选出所有不重复的列名
unique_max_cols = max_cols.unique()
unique_max_cols[:5]

array(['California Institute of Technology',
       'University of Phoenix-Arizona',
       "Mr Leon's School of Hair Design-Moscow",
       'Velvatex College of Beauty Culture',
       'Thunderbird School of Global Management'], dtype=object)

In [80]:
#用max_cols选出只包含最大值的行，用style的highlight_max()高亮
college_n2.loc[unique_max_cols].style.highlight_max()

In [81]:
#用axis参数可以高亮每行的最大值
college = pd.read_csv('data/college.csv',index_col='INSTNM')
college_ugds = college.filter(like='UGDS_').head()
college_ugds.style.highlight_max(axis='columns')

In [82]:
pd.Timedelta(1,unit='Y')

Timedelta('365 days 05:49:12')

# 7.用链式方法重现idxmax

In [4]:
#和前面一样，只选出数值列
college = pd.read_csv('data/college.csv',index_col='INSTNM')
cols = ['MD_EARN_WNE_P10','GRAD_DEBT_MDN_SUPP']
for col in cols:
    college[col] = pd.to_numeric(college[col],errors='coerce')

college_n = college.select_dtypes(include=[np.number])
criteria = college_n.nunique() == 2
binary_cols = college_n.columns[criteria].tolist()
college_n = college_n.drop(labels=binary_cols,axis='columns')

college_n.max().head()

SATVRMID         765.0
SATMTMID         785.0
UGDS          151558.0
UGDS_WHITE         1.0
UGDS_BLACK         1.0
dtype: float64

In [5]:
#college_n.max()可以选出每列的最大值，用eq方法比较DataFrame的每个值和该列的最大值
college_n.eq(college_n.max()).head()

,SATVRMID,SATMTMID,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,
Alabama A & M University,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
University of Alabama at Birmingham,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Amridge University,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
University of Alabama in Huntsville,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Alabama State University,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [6]:
#用any方法，选出至少包含一个True值的行
has_row_max = college_n.eq(college_n.max()).any(axis='columns')
has_row_max.head()

INSTNM
Alabama A & M University               False
University of Alabama at Birmingham    False
Amridge University                     False
University of Alabama in Huntsville    False
Alabama State University               False
dtype: bool

In [7]:
#因为只有18列，has_row_max最多只能有18个True，来看下实际共有多少
college_n.shape

(7535, 18)

In [8]:
has_row_max.sum()

401

In [10]:
#结果很奇怪，这是因为许多百分比的列的最大值是1.转而使用cumsum()累积求和
#说明很多列的最大值有很多
college_n.eq(college_n.max()).cumsum()

,SATVRMID,SATMTMID,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,
Alabama A & M University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
University of Alabama at Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Amridge University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
University of Alabama in Huntsville,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Alabama State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
The University of Alabama,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Central Alabama Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Athens State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Auburn University at Montgomery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Auburn University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Birmingham Southern College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Chattahoochee Valley Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Concordia College Alabama,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
South University-Montgomery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Enterprise State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
James H Faulkner State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Faulkner University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Gadsden State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
New Beginning College of Cosmetology,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Dothan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Hanceville,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Selma,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Herzing University-Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Huntingdon College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Heritage Christian University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
J F Drake State Community and Technical College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jacksonville State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jefferson Davis Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jefferson State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
John C Calhoun State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Strayer University-Lawrenceville,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Piscataway,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Utah County Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
L'esprit Academy - Royal Oak,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
National Career Institute - Jersey City Branch,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Cobb Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Morrow Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Roswell Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Douglasville Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Lithonia Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Savannah Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Augusta Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Columbus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Columbia Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Charleston Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Irving,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Katy,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Northwest Houston,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Plano,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Cedar Hill,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-North Dallas,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-San Antonio,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Stafford,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
WestMed College - Merced,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Vantage College,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
SAE Institute of Technology San Francisco,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Rasmussen College - Overland Park,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
National Personal Training Institute of Cleveland,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Bay Area Medical Academy - San Jose Satellite Location,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Excel Learning Center-San Antonio South,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2

In [11]:
#对累加和再次累加，那么1就只会出现在最大值首次出现的位置
college_n.eq(college_n.max()).cumsum().cumsum()

,SATVRMID,SATMTMID,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,
Alabama A & M University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
University of Alabama at Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Amridge University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
University of Alabama in Huntsville,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Alabama State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
The University of Alabama,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Central Alabama Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Athens State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Auburn University at Montgomery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Auburn University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Birmingham Southern College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Chattahoochee Valley Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Concordia College Alabama,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
South University-Montgomery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Enterprise State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
James H Faulkner State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Faulkner University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Gadsden State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
New Beginning College of Cosmetology,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Dothan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Hanceville,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Selma,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Herzing University-Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Huntingdon College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Heritage Christian University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
J F Drake State Community and Technical College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jacksonville State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jefferson Davis Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jefferson State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
John C Calhoun State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Strayer University-Lawrenceville,7280,7280,390,377025,72407,337703,958,11332,3291,5031,1051,7251,112549,171294,168898,35883,3420,10216
Strayer University-Piscataway,7281,7281,391,377134,72435,337839,959,11334,3292,5032,1052,7252,112593,171360,168953,35895,3421,10218
Utah County Campus,7282,7282,392,377243,72463,337975,960,11336,3293,5033,1053,7253,112637,171426,169008,35907,3422,10220
L'esprit Academy - Royal Oak,7283,7283,393,377352,72491,338111,961,11338,3294,5034,1054,7254,112681,171492,169063,35919,3423,10222
National Career Institute - Jersey City Branch,7284,7284,394,377461,72519,338247,962,11340,3295,5035,1055,7255,112725,171558,169118,35931,3424,10224
Strayer University-Cobb Campus,7285,7285,395,377570,72547,338383,963,11342,3296,5036,1056,7256,112769,171624,169173,35943,3425,10226
Strayer University-Morrow Campus,7286,7286,396,377679,72575,338519,964,11344,3297,5037,1057,7257,112813,171690,169228,35955,3426,10228
Strayer University-Roswell Campus,7287,7287,397,377788,72603,338655,965,11346,3298,5038,1058,7258,112857,171756,169283,35967,3427,10230
Strayer University-Douglasville Campus,7288,7288,398,377897,72631,338791,966,11348,3299,5039,1059,7259,112901,171822,169338,35979,3428,10232
Strayer University-Lithonia Campus,7289,7289,399,378006,72659,338927,967,11350,3300,5040,1060,7260,112945,171888,169393,35991,3429,10234
Strayer University-Savannah Campus,7290,7290,400,378115,72687,339063,968,11352,3301,5041,1061,7261,112989,171954,169448,36003,3430,10236
Strayer University-Augusta Campus,7291,7291,401,378224,72715,339199,969,11354,3302,5042,1062,7262,113033,172020,169503,36015,3431,10238
Strayer University-Columbus,7292,7292,402,378333,72743,339335,970,11356,3303,5043,1063,7263,113077,172086,169558,36027,3432,10240
Strayer University-Columbia Campus,7293,7293,403,378442,72771,339471,971,11358,3304,5044,1064,7264,113121,172152,169613,36039,3433,10242
Strayer University-Charleston Campus,7294,7294,404,378551,72799,339607,972,11360,3305,5045,1065,7265,113165,172218,169668,36051,3434,10244
Strayer University-Irving,7295,7295,405,378660,72827,339743,973,11362,3306,5046,1066,7266,113209,172284,169723,36063,3435,10246
Strayer University-Katy,7296,7296,406,378769,72855,339879,974,11364,3307,5047,1067,7267,113253,172350,169778,36075,3436,10248
Strayer University-Northwest Houston,7297,7297,407,378878,72883,340015,975,11366,3308,5048,1068,7268,113297,172416,169833,36087,3437,10250
Strayer University-Plano,7298,7298,408,378987,72911,340151,976,11368,3309,5049,1069,7269,113341,172482,169888,36099,3438,10252
Strayer University-Cedar Hill,7299,7299,409,379096,72939,340287,977,11370,3310,5050,1070,7270,113385,172548,169943,36111,3439,10254
Strayer University-North Dallas,7300,7300,410,379205,72967,340423,978,11372,3311,5051,1071,7271,113429,172614,169998,36123,3440,10256
Strayer University-San Antonio,7301,7301,411,379314,72995,340559,979,11374,3312,5052,1072,7272,113473,172680,170053,36135,3441,10258
Strayer University-Stafford,7302,7302,412,379423,73023,340695,980,11376,3313,5053,1073,7273,113517,172746,170108,36147,3442,10260
WestMed College - Merced,7303,7303,413,379532,73051,340831,981,11378,3314,5054,1074,7274,113561,172812,170163,36159,3443,10262
Vantage College,7304,7304,414,379641,73079,340967,982,11380,3315,5055,1075,7275,113605,172878,170218,36171,3444,10264
SAE Institute of Technology San Francisco,7305,7305,415,379750,73107,341103,983,11382,3316,5056,1076,7276,113649,172944,170273,36183,3445,10266
Rasmussen College - Overland Park,7306,7306,416,379859,73135,341239,984,11384,3317,5057,1077,7277,113693,173010,170328,36195,3446,10268
National Personal Training Institute of Cleveland,7307,7307,417,379968,73163,341375,985,11386,3318,5058,1078,7278,113737,173076,170383,36207,3447,10270
Bay Area Medical Academy - San Jose Satellite Location,7308,7308,418,380077,73191,341511,986,11388,3319,5059,1079,7279,113781,173142,170438,36219,3448,10272
Excel Learning Center-San Antonio South,7309,7309,419,380186,73219,341647,987,11390,3320,5060,1080,7280,113825,173208,170493,36231,3449,10274

In [12]:
#现在可以用eq方法和1进行比较，然后用any方法，选出所有至少包含一个True值的行
has_row_max2 = college_n.eq(college_n.max()) \
                        .cumsum()\
                        .cumsum()\
                        .eq(1)\
                        .any(axis='columns')
has_row_max2.head()

INSTNM
Alabama A & M University               False
University of Alabama at Birmingham    False
Amridge University                     False
University of Alabama in Huntsville    False
Alabama State University               False
dtype: bool

In [13]:
#查看有多少True值
has_row_max2.sum()

16

In [14]:
#直接通过BOOL索引选出这些学校
idxmax_cols = has_row_max2[has_row_max2].index
idxmax_cols

Index(['Thunderbird School of Global Management',
       'Southwest University of Visual Arts-Tucson', 'ABC Beauty College Inc',
       'Velvatex College of Beauty Culture',
       'California Institute of Technology',
       'Le Cordon Bleu College of Culinary Arts-San Francisco',
       'MTI Business College Inc', 'Dongguk University-Los Angeles',
       'Mr Leon's School of Hair Design-Moscow',
       'Haskell Indian Nations University', 'LIU Brentwood',
       'Medical College of Wisconsin', 'Palau Community College',
       'California University of Management and Sciences',
       'Cosmopolitan Beauty and Tech School', 'University of Phoenix-Arizona'],
      dtype='object', name='INSTNM')

In [15]:
#和idxmax方法的结果比较
set(college_n.idxmax().unique()) == set(idxmax_cols)

True

In [16]:
#耗时比较
%timeit college_n.idxmax().values

2.36 ms ± 155 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [18]:
%timeit college_n.eq(college_n.max()) \
                        .cumsum()\
                        .cumsum()\
                        .eq(1)\
                        .any(axis='columns')\
                        [lambda x:x].index

6.4 ms ± 207 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

# 8.找到最常见的最大值

In [19]:
#读取college，过滤出只包含本科生种族比例信息的列
pd.options.display.max_rows = 40
college = pd.read_csv('data/college.csv',index_col='INSTNM')
college_ugds = college.filter(like='UGDS_')
college_ugds.head()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

In [20]:
#用idxmax方法选出每行种族比例最高的列名
highest_percentage_race = college_ugds.idxmax(axis='columns')
highest_percentage_race.head()

INSTNM
Alabama A & M University               UGDS_BLACK
University of Alabama at Birmingham    UGDS_WHITE
Amridge University                     UGDS_BLACK
University of Alabama in Huntsville    UGDS_WHITE
Alabama State University               UGDS_BLACK
dtype: object

In [21]:
#用value_counts，查看最大值的分布
highest_percentage_race.value_counts(normalize=True)

UGDS_WHITE    0.670352
UGDS_BLACK    0.151586
UGDS_HISP     0.129473
UGDS_UNKN     0.023422
UGDS_ASIAN    0.012074
UGDS_AIAN     0.006110
UGDS_NRA      0.004073
UGDS_NHPI     0.001746
UGDS_2MOR     0.001164
dtype: float64

In [23]:
#对于黑人比例最高的学校，排名第二的种族的分布情况
college_black = college_ugds[highest_percentage_race == 'UGDS_BLACK']
college_black = college_black.drop('UGDS_BLACK',axis='columns')
college_black.idxmax(axis='columns').value_counts(normalize=True)

UGDS_WHITE    0.661228
UGDS_HISP     0.230326
UGDS_UNKN     0.071977
UGDS_NRA      0.018234
UGDS_ASIAN    0.009597
UGDS_2MOR     0.006718
UGDS_NHPI     0.000960
UGDS_AIAN     0.000960
dtype: float64